# Generated by Django 3.0.1 on 2020-01-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200111_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('moves',)},
        ),
    ]
