# Generated by Django 3.0.1 on 2020-02-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200202_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-win', 'lose')},
        ),
        migrations.AddField(
            model_name='profile',
            name='game',
            field=models.IntegerField(default=0),
        ),
    ]
